import { identityInfo } from './modules/security/managed-identity.bicep'

targetScope = 'resourceGroup'

@description('Key-value pairs of tags to assign to all resources. The default azd tags are automatically added.')
param deploymentTags object
var tags = union(azdTags, deploymentTags)
// var _manifest = loadJsonContent('./manifest.json')
// Environment name. This is automatically set by the 'azd' tool.
@description('Environment name used as a tag for all resources. This is directly mapped to the azd-environment.')
param environmentName string = ''

// Tag settings
// default required tags for azd deployment
var azdTags = { 'azd-env-name': environmentName }

var abbrs = loadJsonContent('./abbreviations.json')
var roles = loadJsonContent('./roles.json')

@description('Name of the resource group where all resources will be created. When empty, the name is autogenerated.')
// param resourceGroupName string
var resourceGroupName = resourceGroup().name
var _resourceGroupName = !empty(resourceGroupName) ? resourceGroupName : '${abbrs.managementGovernance.resourceGroup}-${environmentName}'

var suffix = toLower(uniqueString(subscription().id, environmentName, location))
var deploymentStorageContainerName = 'app-package'
@description('Identities to assign roles to.')
param identities identityInfo[] = union([], [{
  principalId: principalId
  principalType: 'User'
}])

@description('Location for the Static Web App and Azure Function App. Only the following locations are allowed: centralus, eastus2, westeurope, westus2, southeastasia')
param location string

@description('Location for the Azure AI Foundry account')
@allowed([
  'East US'
  'East US 2'
  'France Central'
  'Germany West Central'
  'Japan East'
  'Korea Central'
  'North Central US'
  'Norway East'
  'Poland Central'
  'South Africa North'
  'South Central US'
  'South India'
  'Southeast Asia'
  'Spain Central'
  'Sweden Central'
  'Switzerland North'
  'Switzerland West'
  'UAE North'
  'UK South'
  'West Europe'
  'West US'
  'West US 3'
])
param aoaiLocation string

@description('Network isolation? If yes it will create the private endpoints.')
@allowed([false, true])
param networkIsolation bool
var _networkIsolation = networkIsolation

@minLength(6)
@maxLength(72)
@description('Test vm gpt user password. Use strong password with letters and numbers. Needed only when choosing network isolation and create bastion option. If not creating with network isolation you can write anything. Password must be between 6-72 characters long and must satisfy at least 3 of password complexity requirements from the following: 1-Contains an uppercase character, 2-Contains a lowercase character, 3-Contains a numeric digit, 4-Contains a special character, 5- Control characters are not allowed.')
@secure()
param vmUserInitialPassword string

@description('Deploy VM? If yes it will create the virtual machine to access the network isolated environment in the zero trust configuration.')
@allowed([false, true])
param deployVM bool
var _deployVM = deployVM

@description('Deploy VPN?')
@allowed([false, true])
param deployVPN bool = false
var _deployVPN = deployVPN

@description('Test vm gpt user name. Needed only when choosing network isolation and create bastion option. If not you can leave it blank.')
param vmUserName string = ''
var _vmUserName = !empty(vmUserName) ? vmUserName : 'adp-user'


@allowed([false, true])
param multiModal bool = false
var _multiModal = multiModal

@allowed([false, true])
param ai_vision_enabled bool = false
var _ai_vision_enabled = ai_vision_enabled

// PricipalId that will have access to KeyVault secrets, this is automatically set by the 'azd' tool to the principal runing azd
@description('Id of the user or app to assign application roles')
param principalId string = ''

@description('The name of the Zero Trust VM. If left empty, a random name will be generated.')
param ztVmName string = ''
var _ztVmName = !empty(ztVmName) ? ztVmName : 'vm-${take(suffix, 12)}'

@description('The name of the VM Key Vault Secret. If left empty, a random name will be generated.')
param vmKeyVaultSecName string = ''
var _vmKeyVaultSecName = !empty(vmKeyVaultSecName) ? vmKeyVaultSecName : 'vmUserInitialPassword'

@description('Size of the test VM')
param vmSize string = 'Standard_D8s_v5'

@description('Image SKU (e.g., win11-25h2-ent, win11-23h2-ent, 2022-datacenter).')
param vmImageSku string = 'win11-25h2-ent'

@description('Image publisher (Windows 11: MicrosoftWindowsDesktop, Windows Server: MicrosoftWindowsServer).')
param vmImagePublisher string = 'MicrosoftWindowsDesktop'

@description('Image offer (Windows 11: windows-11, Windows Server: WindowsServer).')
param vmImageOffer string = 'windows-11'

@description('Image version (use latest unless you need a pinned build).')
param vmImageVersion string = 'latest'

// flag that indicates if we're reusing a vnet
var _vnetReuse = _azureReuseConfig.vnetReuse

@description('Virtual network name, you can leave as it is to generate a random name.')
param vnetName string = ''
var _vnetName = _azureReuseConfig.vnetReuse ? _azureReuseConfig.existingVnetName : !empty(vnetName) ? vnetName : '${abbrs.networking.virtualNetwork}ai-${suffix}'

@description('Address space for the virtual network')
param vnetAddress string = ''
var _vnetAddress = !empty(vnetAddress) ? vnetAddress : '10.0.0.0/23'

@description('Forked Git repository URL for the Static Web App')
param userPrincipalId string

// Environment name. This is automatically set by the 'azd' tool.
@description('Environment name used as a tag for all resources. This is directly mapped to the azd-environment.')
// param environmentName string = 'dev'

@allowed(['Dedicated', 'FlexConsumption'])
param functionAppHostPlan string

@allowed(['B1', 'B2', 'S1', 'S2', 'S3', 'P1v2', 'P2v2', 'P3v2', 'FC1'])
param functionAppSKU string = (functionAppHostPlan == 'FlexConsumption') ? 'FC1' : 'S2'

var openaiApiVersion = '2025-08-07'
var openaiModel = 'gpt-5-mini'
var functionRuntime = 'python'

var hostingPlanName = '${abbrs.compute.appServicePlan}${suffix}'
var processingFunctionAppName = '${abbrs.compute.functionApp}processing-${suffix}'
var storageAccountName = '${abbrs.storage.storageAccount}${suffix}data'
var funcStorageName = '${abbrs.storage.storageAccount}${suffix}func'
var keyVaultName = '${abbrs.security.keyVault}${suffix}'
var aiFoundryName = '${abbrs.ai.aiFoundry}${suffix}'
var cosmosAccountName = '${abbrs.databases.cosmosDBDatabase}${suffix}'
var appInsightsName = '${abbrs.managementGovernance.applicationInsights}${suffix}'
var logAnalyticsName = '${abbrs.managementGovernance.logAnalyticsWorkspace}${suffix}'
var appConfigName = '${abbrs.configuration.appConfiguration}${suffix}'

var promptsContainer = 'promptscontainer'
var configContainerName = 'config'
var conversationHistoryContainerName = 'conversationhistory'
var cosmosDatabaseName = 'conversationHistoryDB'


@description('The name of the Azure Cosmos DB Private Endpoint. If left empty, a random name will be generated.')
param azureDbAccountPe string = ''
var _azureDbAccountPe = !empty(azureDbAccountPe) ? azureDbAccountPe : '${abbrs.databases.cosmosDBDatabase}${abbrs.networking.privateEndpoint}${suffix}'

@description('The name of the Azure Configuration Private Endpoint. If left empty, a random name will be generated.')
param azureAppConfigPe string = ''
var _azureAppConfigPe = !empty(azureAppConfigPe) ? azureAppConfigPe : '${abbrs.configuration.appConfiguration}${abbrs.networking.privateEndpoint}${suffix}'

@description('The name of the Azure AI Services Private Endpoint. If left empty, a random name will be generated.')
param azureAiServicesPe string = ''
var _azureAiServicesPe = !empty(azureAiServicesPe) ? azureAiServicesPe : '${abbrs.ai.aiServices}${abbrs.networking.privateEndpoint}${suffix}'


@description('The name of the Azure Storage Account Private Endpoint. If left empty, a random name will be generated.')
param azureBlobStorageAccountPe string = ''
var _azureBlobStorageAccountPe = !empty(azureBlobStorageAccountPe) ? azureBlobStorageAccountPe : '${abbrs.storage.storageAccount}blob${abbrs.networking.privateEndpoint}${suffix}'

param azureTableStorageAccountPe string = ''
var _azureTableStorageAccountPe = !empty(azureTableStorageAccountPe) ? azureTableStorageAccountPe : '${abbrs.storage.storageAccount}table${abbrs.networking.privateEndpoint}${suffix}'

param azureQueueStorageAccountPe string = ''
var _azureQueueStorageAccountPe = !empty(azureQueueStorageAccountPe) ? azureQueueStorageAccountPe : '${abbrs.storage.storageAccount}queue${abbrs.networking.privateEndpoint}${suffix}'

param azureFileStorageAccountPe string = ''
var _azureFileStorageAccountPe = !empty(azureFileStorageAccountPe) ? azureFileStorageAccountPe : '${abbrs.storage.storageAccount}file${abbrs.networking.privateEndpoint}${suffix}'

@description('The name of the Azure Storage Account Private Endpoint. If left empty, a random name will be generated.')
param processingFuncAppPe string = ''
var _processingfunctionAppPe = !empty(processingFuncAppPe) ? processingFuncAppPe : 'func-proc-${abbrs.networking.privateEndpoint}${suffix}'

@description('The name of the Azure Key Vault Private Endpoint. If left empty, a random name will be generated.')
param azureKeyvaultPe string = ''
var _azureKeyvaultPe = !empty(azureKeyvaultPe) ? azureKeyvaultPe : '${abbrs.security.keyVault}${abbrs.networking.privateEndpoint}${suffix}'

// resource resourceGroup 'Microsoft.Resources/resourceGroups@2024-03-01' = {
//   name: _resourceGroupName
//   location: location
//   tags: union(tags, {})
// }

module logAnalyticsWorkspace './modules/management_governance/log-analytics-workspace.bicep' = {
  // // scope : resourceGroup
  name: logAnalyticsName
  params: {
    name: logAnalyticsName
    location: location
    retentionInDays: 30
    publicNetworkAccessForIngestion: _networkIsolation?'Disabled':'Enabled'
    publicNetworkAccessForQuery: _networkIsolation?'Disabled':'Enabled'
  }
}

module azureMonitorPrivateLinkScope './modules/security/private-link-scope.bicep' = if (_networkIsolation && !_vnetReuse) {
  // // scope: ResourceGroup
  name: '${abbrs.networking.privateLink}${suffix}'
  params: {
    privateLinkScopeName: '${abbrs.networking.privateLink}${suffix}'
    privateLinkScopedResources: [
      logAnalyticsWorkspace.outputs.id
      appInsights.outputs.id
    ]
  }
}

module automationDnsZone './modules/network/private-dns-zones.bicep' = if (_networkIsolation && !_vnetReuse) {
  name: 'automation-dnzones'
  // // scope: ResourceGroup
  params: {
    dnsZoneName: 'privatelink.agentsvc.azure-automation.net'
    tags: tags
    virtualNetworkName: _networkIsolation?vnet.outputs.name:''
  }
}

module odsInsightsDnsZone './modules/network/private-dns-zones.bicep' = if (_networkIsolation && !_vnetReuse) {
  name: 'odsinsights-dnzones'
  // // scope: ResourceGroup
  params: {
    dnsZoneName: 'privatelink.ods.opinsights.azure.com'
    tags: tags
    virtualNetworkName: _networkIsolation?vnet.outputs.name:''
  }
}

module omsInsightsDnsZone './modules/network/private-dns-zones.bicep' = if (_networkIsolation && !_vnetReuse) {
  name: 'omsinsights-dnzones'
  // // scope: ResourceGroup
  params: {
    dnsZoneName: 'privatelink.oms.opinsights.azure.com'
    tags: tags
    virtualNetworkName: _networkIsolation?vnet.outputs.name:''
  }
}

module azMonitorDnsZone './modules/network/private-dns-zones.bicep' = if (_networkIsolation && !_vnetReuse) {
  name: 'azmonitor-dnzones'
  // // scope: ResourceGroup
  params: {
    dnsZoneName: 'privatelink.monitor.azure.com'
    tags: tags
    virtualNetworkName: _networkIsolation?vnet.outputs.name:''
  }
}

var logAnalyticsPEName = '${abbrs.managementGovernance.logAnalyticsWorkspace}${abbrs.security.privateEndpoint}${suffix}'
module logAnalyticsPe './modules/network/private-endpoint.bicep' = if (_networkIsolation && !_vnetReuse) {
  name: logAnalyticsPEName
  // // scope: ResourceGroup
  params: {
    location: location
    name: logAnalyticsPEName
    tags: tags
    subnetId: _networkIsolation?vnet.outputs.aiSubId:''
    serviceId: azureMonitorPrivateLinkScope.outputs.id
    groupIds: ['azuremonitor']
    dnsZoneId: _networkIsolation?azMonitorDnsZone.outputs.id:''
  }
}

// App Insights Module
module appInsights './modules/management_governance/application-insights.bicep' = {
  // // scope : resourceGroup
  name: appInsightsName
  params: {
    name: appInsightsName
    location: location
    appInsightsReuse : false
    logAnalyticsReuse: false
    existingAppInsightsResourceGroupName : resourceGroup().name
    logAnalyticsWorkspaceId: logAnalyticsWorkspace.outputs.id
    suffix : suffix
    publicNetworkAccessForIngestion: _networkIsolation?'Disabled':'Enabled'
    publicNetworkAccessForQuery: _networkIsolation?'Disabled':'Enabled'
  }
}

// var secureAppSettings = [
//   {
//     name: 'OPENAI_API_KEY'
//     value: aoaiAccountModule.outputs.AOAI_API_KEY
//   }
// ]

var appSettings = [
  {
    name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
    value: appInsights.outputs.connectionString
  }
  {
    name: 'FUNC_STORAGE_ACCOUNT_NAME'
    value : funcStorageName
  }
  {
    name: 'COSMOS_DB_CONVERSATION_HISTORY_CONTAINER'
    value: conversationHistoryContainerName
  }
  {
    name: 'COSMOS_DB_URI'
    value: 'https://${cosmos.outputs.accountName}.documents.azure.com:443/'
  }
  {
    name: 'DATA_STORAGE_ACCOUNT_NAME'
    value: storageAccountName
  }
  {
    name: 'DATA_STORAGE_ENDPOINT'
    value: 'https://${storageAccountName}.blob.${environment().suffixes.storage}'
  }
  {
    name: 'PROMPT_FILE'
    value: 'prompts.yaml'
  }
  {
    name: 'OPENAI_API_VERSION'
    value: '2024-05-01-preview'
  }
  {
    name: 'OPENAI_API_BASE'
    //jamespace
    // Migration: Construct endpoint from AVM output name (AVM only outputs names, not URLs)
    value: 'https://${aiFoundry.outputs.aiServicesName}.cognitiveservices.azure.com/'
  }
  {
    name: 'AI_SERVICES_ENDPOINT'
    value: 'https://${aiFoundry.outputs.aiServicesName}.cognitiveservices.azure.com/'
  }
  {
    name: 'OPENAI_API_EMBEDDING_MODEL'
    value: 'text-embedding-ada-002'
  }
  {
    name: 'OPENAI_MODEL'
    value: 'gpt-5-mini'
  }
  {
    name: 'COSMOS_DB_DATABASE_NAME'
    value: cosmos.outputs.databaseName
  }
  {
    name: 'PROCESSING_FUNCTION_APP_NAME'
    value: processingFunctionAppName
  }
  {
    name: 'PROCESSING_FUNCTION_APP_URL'
    value: '${processingFunctionAppName}.azurewebsites.net'
  }
  {
    name: 'SAS_TOKEN_EXPIRY_HOURS'
    value: 24
  }
  {
    name : 'USE_SAS_TOKEN'
    value: 'false'
  }
  {
    name: 'FINAL_OUTPUT_CONTAINER'
    value: 'silver'
  }
]

module vaultDnsZone './modules/network/private-dns-zones.bicep' = if (_networkIsolation && !_vnetReuse) {
  // // scope : resourceGroup
  name: 'vault-dnzones'
  params: {
    dnsZoneName: 'privatelink.vaultcore.azure.net' 
    tags: tags
    virtualNetworkName: _networkIsolation?vnet.outputs.name:''
  }
}

module keyvaultpe './modules/network/private-endpoint.bicep' = if (_networkIsolation && !_vnetReuse) {
  // // scope : resourceGroup
  name: 'keyvaultpe'
  params: {
    location: location
    name: _azureKeyvaultPe
    tags: tags
    subnetId: _networkIsolation?vnet.outputs.aiSubId:''
    serviceId: keyVault.outputs.id
    groupIds: ['Vault']
    dnsZoneId: _networkIsolation?vaultDnsZone.outputs.id:''
  }
}

var keyVaultSecretsUserIdentityAssignments = [
  for identity in identities: {
    principalId: identity.principalId
    roleDefinitionId: keyVaultSecretsUserRole.id
    principalType: identity.principalType
  }
]
// 
var keyVaultSecretsUserIdentityAssignmentsAll = concat(keyVaultSecretsUserIdentityAssignments,
[
  {
    principalId: uaiFrontendMsi.outputs.principalId
    roleDefinitionId: keyVaultSecretsUserRole.id
    principalType: 'ServicePrincipal'
  }
])

var subnets = reduce(
  map(vnet.outputs.subnets, subnet => {
      '${subnet.name}': {
        id: subnet.id
        addressPrefix: subnet.properties.addressPrefix
      }
    }),
  {},
  (cur, acc) => union(cur, acc)
)

// 1. Key Vault
module keyVault './modules/security/key-vault.bicep' = {
  // scope : resourceGroup
  name: 'keyVaultModule'
  params: {
    name: keyVaultName
    location: location
    //tenantId: tenantId
    keyVaultReuse: _azureReuseConfig.keyVaultReuse
    existingKeyVaultResourceGroupName: resourceGroupName
    // secureAppSettings: secureAppSettings
    publicNetworkAccess: _networkIsolation?'Disabled':'Enabled'
    roleAssignments: concat(keyVaultSecretsUserIdentityAssignmentsAll, [])
    // subnets : (_networkIsolation && !_vnetReuse) ? [
    //   {
    //     name: 'aiSubId'
    //     id: _networkIsolation?vnet.outputs.aiSubId:''
    //   }
    //   {
    //     name: 'databaseSubId'
    //     id: _networkIsolation?vnet.outputs.databaseSubId:''
    //   }
    //   {
    //     name: 'appIntSubId'
    //     id: _networkIsolation?vnet.outputs.appIntSubId:''
    //   }
    //   {
    //     name: 'appServiceSubId'
    //     id: _networkIsolation?vnet.outputs.appServicesSubId:''
    //   }
    // ] : []
  }
}

module keyVaultAccessFunc1 './modules/rbac/keyvault-access.bicep' = {
  // scope : resourceGroup
  name: 'keyvault-access-${processingFunctionAppName}'
  params: {
    principalId: uaiFrontendMsi.outputs.principalId
    roleDefinitionId: keyVaultSecretsUserRole.id
    principalType: 'ServicePrincipal'
    resourceName: keyVault.outputs.name
  }
}

module keyVaultAccessPolicies './modules/rbac/keyvault-access-policy.bicep' = {
  // scope : resourceGroup
  name: 'keyvault-access-${keyVaultName}'
  params: {
    permissions: {
      secrets: [ 'get', 'list', 'set', 'delete' ]
    }
    principalId: uaiFrontendMsi.outputs.principalId
    resourceName: keyVault.outputs.name
  }
}

module keyVaultAdmin './modules/rbac/role.bicep' = {
  // scope : resourceGroup
  name: 'keyvault-admin-${keyVaultName}'
  params: {
    principalId: principalId
    roleDefinitionId: roles.security.keyVaultAdministrator
    principalType: 'User'
  }
}


module cosmosContributorProcessor './modules/rbac/cosmos-contributor.bicep' = {
  name: 'processingcosmosContributorModule'
  // scope: resourceGroup // Role assignment applies to the storage account
  params: {
    principalId: uaiFrontendMsi.outputs.principalId
    resourceName: cosmos.outputs.accountName
  }
}

// Invoke the role assignment module for Storage Queue Data Contributor
module cosmosContributorUser './modules/rbac/cosmos-contributor.bicep' = {
  name: 'cosmosContributorUserModule'
  // // scope: resourceGroup // Role assignment applies to the storage account
  params: {
    principalId: userPrincipalId
    resourceName: cosmos.outputs.accountName
  }
}

module cogservicesDnsZone './modules/network/private-dns-zones.bicep' = if (_networkIsolation && !_vnetReuse) {
  // scope : resourceGroup
  name: 'aiservices-dnzones'
  params: {
    dnsZoneName: 'privatelink.cognitiveservices.azure.com' 
    tags: tags
    virtualNetworkName: _networkIsolation?vnet.outputs.name:''
  }
}

module openaiDnsZone './modules/network/private-dns-zones.bicep' = if (_networkIsolation && !_vnetReuse) {
  name: 'openai-dnzones'
  // scope: resourceGroup
  params: {
    dnsZoneName: 'privatelink.openai.azure.com'
    tags: tags
    virtualNetworkName: _networkIsolation?vnet.outputs.name:''
  }
}


module aiServicesDnsZone './modules/network/private-dns-zones.bicep' = if (_networkIsolation && !_vnetReuse) {
  // scope : resourceGroup
  name: 'aiservices-services-dnzones'
  params: {
    dnsZoneName: 'privatelink.services.ai.azure.com'
    tags: tags
    virtualNetworkName: _networkIsolation?vnet.outputs.name:''
  }
}



//jamespace
// Migration: aiServicesPe REMOVED - AVM handles private endpoint creation internally

// Cosmos DB Module
module documentsDnsZone './modules/network/private-dns-zones.bicep' = if (_networkIsolation && !_vnetReuse) {
  // scope : resourceGroup
  name: 'documents-dnzones'
  params: {
    dnsZoneName: 'privatelink.documents.azure.com' 
    tags: tags
    virtualNetworkName: _networkIsolation?vnet.outputs.name:''
  }
}

module cosmospe './modules/network/private-endpoint.bicep' = if (_networkIsolation && !_vnetReuse) {
  // scope : resourceGroup
  name: 'cosmospe'
  params: {
    location: location
    name: _azureDbAccountPe
    tags: tags
    subnetId: _networkIsolation?vnet.outputs.databaseSubId:''
    serviceId: cosmos.outputs.id
    groupIds: ['Sql']
    dnsZoneId: _networkIsolation?documentsDnsZone.outputs.id:''
  }
}

// 4. Cosmos DB
module cosmos './modules/db/cosmos.bicep' = {
  // scope : resourceGroup
  name: 'cosmosModule'
  params: {
    location: location
    accountName: cosmosAccountName
    databaseName: cosmosDatabaseName
    containerName: promptsContainer
    configContainerName: configContainerName
    conversationContainerName: conversationHistoryContainerName
    cosmosDbReuse: _azureReuseConfig.cosmosDbReuse
    datasourcesContainerName: configContainerName
    existingCosmosDbAccountName: _azureReuseConfig.existingCosmosDbAccountName
    existingCosmosDbResourceGroupName: _azureReuseConfig.existingCosmosDbResourceGroupName
    keyVaultName: keyVault.outputs.name
    publicNetworkAccess: _networkIsolation?'Disabled':'Enabled'
  }
}

//jamespace
// 2. AI Foundry (replacing Azure OpenAI)
// Migration: Using AVM pattern module with includeAssociatedResources: false
// Note: baseName max 12 chars, so using substring of suffix
var aiFoundryBaseName = substring(suffix, 0, 12)

module aiFoundry 'br/public:avm/ptn/ai-ml/ai-foundry:0.6.0' = {
  name: 'aiFoundryDeployment'
  params: {
    // Required: baseName is used for naming resources (max 12 chars)
    baseName: aiFoundryBaseName
    
    // includeAssociatedResources: false means we don't want AVM to create 
    // Key Vault, Storage, CosmosDB, AI Search - we have our own
    includeAssociatedResources: false
    
    // AI Foundry configuration with location and networking
    aiFoundryConfiguration: {
      // Use our existing aoaiName for the account name
      accountName: aiFoundryName
      location: aoaiLocation
      // Keep API key authentication enabled for local development
      disableLocalAuth: false
      // Networking configuration (only when network isolation is enabled)
      networking: _networkIsolation ? {
        //jamespace
        // DNS zones - pass existing zone IDs (AVM doesn't create them)
        cognitiveServicesPrivateDnsZoneResourceId: cogservicesDnsZone.outputs.id
        openAiPrivateDnsZoneResourceId: openaiDnsZone.outputs.id
        aiServicesPrivateDnsZoneResourceId: aiServicesDnsZone.outputs.id
      } : null
    }
    
    // Private endpoint subnet (for network isolation)
    privateEndpointSubnetResourceId: _networkIsolation ? vnet.outputs.aiSubId : ''
    
    // Model deployments - using correct AVM schema
    aiModelDeployments: [
      {
        name: 'gpt-5-mini'
        model: {
          format: 'OpenAI'
          name: 'gpt-5-mini'
          version: '2025-08-07'
        }
        sku: {
          name: 'GlobalStandard'
          capacity: 100
        }
      }
      {
        name: 'text-embedding-ada-002'
        model: {
          format: 'OpenAI'
          name: 'text-embedding-ada-002'
          version: '2'
        }
        sku: {
          name: 'Standard'
          capacity: 100
        }
      }
    ]
  }
  dependsOn: _networkIsolation ? [vnet, aiServicesDnsZone, cogservicesDnsZone, openaiDnsZone] : []
}

module vnet './modules/network/vnet.bicep' = if (_networkIsolation && !_vnetReuse) {
  // scope : resourceGroup
  name: 'virtual-network'
  params: {
    location: location
    vnetName: _vnetName
    vnetReuse: _vnetReuse
    deployVPN: _deployVPN
    existingVnetResourceGroupName: _azureReuseConfig.existingVnetResourceGroupName
    tags: tags
    vnetAddress: _vnetAddress
    appServicePlanId: hostingPlan.outputs.resourceId
    appServicePlanName: hostingPlan.outputs.name
  }
}

module vpnGateway './modules/network/vnet-vpn-gateway.bicep' = if (_networkIsolation && !_vnetReuse && _deployVPN) {
  // scope : resourceGroup
  name: 'vpn-gateway'
  params: {
    location: location
    vnetName: _vnetName
    tags: tags
  }
}

module appConfigDnsZone './modules/network/private-dns-zones.bicep' = if (_networkIsolation && !_vnetReuse) {
  // scope : resourceGroup
  name: 'appconfig-dnzones'
  //scope: resourceGroup
  params: {
    dnsZoneName: 'privatelink.azconfig.io' 
    tags: tags
    virtualNetworkName: _networkIsolation?vnet.outputs.name:''
  }
}

module appConfigPe './modules/network/private-endpoint.bicep' = if (_networkIsolation && !_vnetReuse) {
  // scope : resourceGroup
  name: 'appConfigPe'
  params: {
    location: location
    name: _azureAppConfigPe
    tags: tags
    subnetId: _networkIsolation?vnet.outputs.aiSubId:''
    serviceId: appConfig.outputs.id
    groupIds: ['configurationStores']
    dnsZoneId: _networkIsolation?appConfigDnsZone.outputs.id:''
  }
}

var appConfigurationManagedIdentityName = '${abbrs.security.managedIdentity}${abbrs.configuration.appConfiguration}${suffix}'
module applicationManagedIdentity './modules/security/managed-identity.bicep' = {
  // scope: resourceGroup
  name: appConfigurationManagedIdentityName
  params: {
    name: appConfigurationManagedIdentityName
    location: location
    tags: union(tags, {})
  }
}

module appConfig './modules/app_config/appconfig.bicep' = {
  // scope : resourceGroup
  name: 'appconfig'
  params: {
    name : appConfigName
    //administratorObjectId: principalId
    //administratorPrincipalType: 'User'
    //actionGroupId: ''
    appSettings: appSettings
    secureAppSettings: keyVault.outputs.secrets
    location: location
    tags: tags
    identityId: applicationManagedIdentity.outputs.id
    //logAnalyticsWorkspaceResourceId: _azureReuseConfig.existingLogAnalyticsWorkspaceResourceId ?? ''
    //vaultName: keyVault.outputs.name
    //privateDnsZones: []
    resourceToken: suffix
    //timestamp: ''
    //subnetId: (_networkIsolation && !_vnetReuse)?vnet.outputs.appIntSubId:''
    //uaiId: ''  //uaiAppConfig.id
    publicNetworkAccess: 'Enabled'
  }
}

module blobDnsZone './modules/network/private-dns-zones.bicep' = if (_networkIsolation && !_vnetReuse) {
  // scope : resourceGroup
  name: 'blob-dnzones'
  params: {
    dnsZoneName: 'privatelink.blob.${environment().suffixes.storage}' 
    tags: tags
    virtualNetworkName: _networkIsolation?vnet.outputs.name:''
  }
}

module queueDnsZone './modules/network/private-dns-zones.bicep' = if (_networkIsolation && !_vnetReuse) {
  // scope : resourceGroup
  name: 'queue-dnzones'
  params: {
    dnsZoneName: 'privatelink.queue.${environment().suffixes.storage}' 
    tags: tags
    virtualNetworkName: _networkIsolation?vnet.outputs.name:''
  }
}

module tableDnsZone './modules/network/private-dns-zones.bicep' = if (_networkIsolation && !_vnetReuse) {
  // scope : resourceGroup
  name: 'table-dnzones'
  params: {
    dnsZoneName: 'privatelink.table.${environment().suffixes.storage}' 
    tags: tags
    virtualNetworkName: _networkIsolation?vnet.outputs.name:''
  }
}

module fileDnsZone './modules/network/private-dns-zones.bicep' = if (_networkIsolation && !_vnetReuse) {
  // scope : resourceGroup
  name: 'file-dnzones'
  params: {
    dnsZoneName: 'privatelink.file.${environment().suffixes.storage}' 
    tags: tags
    virtualNetworkName: _networkIsolation?vnet.outputs.name:''
  }
}

module storagePe './modules/storage/storage-private-endpoints.bicep' = if (_networkIsolation && !_vnetReuse){
  // scope : resourceGroup
  name: 'storage-pe'
  dependsOn: [
    vnet
    storage
    blobDnsZone
    queueDnsZone
    tableDnsZone
    fileDnsZone
  ]
  params: {
    location: location
    name: storageAccountName
    tags: tags
    vnetName: _vnetName
  }
}

module storage './modules/storage/storage-account.bicep' = {
  // scope : resourceGroup
  name: 'storage'
  params: {
    name: storageAccountName
    location: location
    storageReuse: _azureReuseConfig.storageReuse
    existingStorageResourceGroupName: _azureReuseConfig.existingStorageResourceGroupName
    tags: tags
    publicNetworkAccess: _networkIsolation?'Disabled':'Enabled'
    allowBlobPublicAccess: false // Disable anonymous access
    containers: [
      { name: 'bronze', publicAccess: 'None' }
      { name: 'silver', publicAccess: 'None' }
      { name: 'gold', publicAccess: 'None' }      
      { name: 'prompts', publicAccess: 'None' }      
    ]
    deleteRetentionPolicy: {
      enabled: true
      days: 7
    }
    networkAcls : {
      resourceAccessRules :[]
      bypass: 'AzureServices'
      defaultAction: _networkIsolation?'Deny':'Allow'
      ipRules : []
      virtualNetworkRules : (_networkIsolation && !_vnetReuse) ? [
        {
          id: vnet.outputs.aiSubId
          action: 'Allow'
        }
      ] : []
    }
  }  
}

module procStoragePe './modules/storage/storage-private-endpoints.bicep' = if (_networkIsolation && !_vnetReuse){
  // scope : resourceGroup
  name: 'proc-storage-pe'
  dependsOn: [
    vnet
    procFuncStorage
    queueDnsZone
    tableDnsZone
    fileDnsZone
  ]
  params: {
    location: location
    name: funcStorageName
    tags: tags
    vnetName: _vnetName
  }
}

// module procFuncStorage './modules/storage/storage-account.bicep' = {
//   scope : resourceGroup
//   name: 'procfuncstorage'
//   params: {
//     name: funcStorageName // '${abbrs.storage.storageAccount}${suffix}func'
//     location: location
//     storageReuse: _azureReuseConfig.storageReuse
//     existingStorageResourceGroupName: _azureReuseConfig.existingStorageResourceGroupName
//     tags: tags
//     publicNetworkAccess: _networkIsolation?'Disabled':'Enabled'
//     allowBlobPublicAccess: false // Disable anonymous access
//     deleteRetentionPolicy: {
//       enabled: true
//       days: 7
//     }
//     networkAcls : {
//       resourceAccessRules :[]
//       bypass: 'AzureServices'
//       defaultAction: _networkIsolation?'Deny':'Allow'
//       ipRules : []
//       virtualNetworkRules : (_networkIsolation && !_vnetReuse) ? [
//         {
//           id: vnet.outputs.aiSubId
//           action: 'Allow'
//         }
//       ] : []
//     }
//   }  
// }

module procFuncStorage 'br/public:avm/res/storage/storage-account:0.25.0' = {
  name: 'procfuncstorage'
  // scope: resourceGroup
  params: {
    name: funcStorageName
    allowBlobPublicAccess: true
    allowSharedKeyAccess: false // Disable local authentication methods as per policy
    dnsEndpointType: 'Standard'
    publicNetworkAccess: _networkIsolation?'Disabled':'Enabled'
    networkAcls: {
      defaultAction:  _networkIsolation?'Deny':'Allow'
      bypass: 'AzureServices'
      virtualNetworkRules: (_networkIsolation && !_vnetReuse) ? [
        {
          id: vnet.outputs.aiSubId
          action: 'Allow'
        }
      ] : []
      ipRules: []
      resourceAccessRules: []
    }
    blobServices: {
      containers: [{name: deploymentStorageContainerName}]
    }
    tableServices:{}
    queueServices: {}
    minimumTlsVersion: 'TLS1_2'  // Enforcing TLS 1.2 for better security
    location: location
    tags: tags
  }
}

// @allowed(['Consumption', 'Premium', 'Dedicated'])
// param functionAppHostPlan string

// @allowed(['S3', 'B2', 'P1v2', 'P2v2', 'P3v2', 'FC1']) if 
// param functionAppSKU string

module hostingPlan 'br/public:avm/res/web/serverfarm:0.1.1' = {
  // scope : resourceGroup
  name: 'hostingPlan'
  params: {
    name: hostingPlanName
    location: location
    sku: {
      name: functionAppSKU
      tier: functionAppHostPlan
    }
    reserved: true
    tags: tags
    zoneRedundant: false
  }
}

module websitesDnsZone './modules/network/private-dns-zones.bicep' = if (_networkIsolation && !_vnetReuse) {
  // scope : resourceGroup
  name: 'websites-dnszones'
  params: {
    dnsZoneName: 'privatelink.azurewebsites.net' 
    tags: tags
    virtualNetworkName: _networkIsolation?vnet.outputs.name:''
  }
}

module processingFunctionAppPe './modules/network/private-endpoint.bicep' = if (_networkIsolation && !_vnetReuse) {
  // scope : resourceGroup
  name: _processingfunctionAppPe
  params: {
    location: location
    name: _processingfunctionAppPe
    tags: tags
    subnetId: _networkIsolation?vnet.outputs.aiSubId:''
    serviceId: processingFunctionApp.outputs.resourceId
    groupIds: ['sites']
    dnsZoneId: _networkIsolation?websitesDnsZone.outputs.id:''
  }
}

module uaiFrontendMsi './modules/security/managed-identity.bicep' = {
  // scope: resourceGroup
  name: '${abbrs.security.managedIdentity}${processingFunctionAppName}'
  params: {
    name: 'uai-${processingFunctionAppName}'
    location: location
    tags: union(tags, {})
  }
}


var commonAppSettings = {
  AZURE_TENANT_ID: subscription().tenantId
  AZURE_CLIENT_ID: uaiFrontendMsi.outputs.clientId
  allow_environment_variables: 'true'
  APP_CONFIGURATION_URI: 'https://${appConfigName}.azconfig.io'
  WEBSITE_VNET_ROUTE_ALL: networkIsolation ? '1' : '0'
  WEBSITE_DNS_SERVER: networkIsolation ? '168.63.129.16' : ''
  WEBSITE_HTTPLOGGING_RETENTION_DAYS: '7'
  FUNCTIONS_EXTENSION_VERSION: '~4'
  APPINSIGHTS_INSTRUMENTATIONKEY: appInsights.outputs.instrumentationKey
  // ApplicationInsights__InstrumentationKey: appInsights.outputs.instrumentationKey

  AzureWebJobsStorage__credential: 'managedidentity'
  AzureWebJobsStorage__clientId: uaiFrontendMsi.outputs.clientId
  AzureWebJobsStorage__accountName: funcStorageName

  DataStorage__clientId: uaiFrontendMsi.outputs.clientId
  DataStorage__accountName: storageAccountName
  DataStorage__credential: 'managedidentity'

}

var flexConsumptionAppSettings = (functionAppHostPlan == 'FlexConsumption') ? {
  APPLICATIONINSIGHTS_CONNECTION_STRING: appInsights.outputs.connectionString
  APPLICATIONINSIGHTS_AUTHENTICATION_STRING: 'Authorization=AAD'
  AzureWebJobsStorage__blobServiceUri: 'https://${funcStorageName}.blob.${environment().suffixes.storage}'
  AzureWebJobsStorage__queueServiceUri: 'https://${funcStorageName}.queue.${environment().suffixes.storage}'
  AzureWebJobsStorage__tableServiceUri: 'https://${funcStorageName}.table.${environment().suffixes.storage}'
  DataStorage__blobServiceUri: 'https://${storageAccountName}.blob.${environment().suffixes.storage}'
  DataStorage__queueServiceUri: 'https://${storageAccountName}.queue.${environment().suffixes.storage}'
  DataStorage__tableServiceUri: 'https://${storageAccountName}.table.${environment().suffixes.storage}'
} : {}

var dedicatedAppSettings = (functionAppHostPlan != 'FlexConsumption') ? {
  FUNCTIONS_WORKER_RUNTIME: functionRuntime
  AzureWebJobsFeatureFlags: 'EnableWorkerIndexing'
  ENABLE_ORYX_BUILD: 'true'
  SCM_DO_BUILD_DURING_DEPLOYMENT: 'true'
} : {}

var planSpecificAppSettings = functionAppHostPlan == 'FlexConsumption'
  ? flexConsumptionAppSettings
  : dedicatedAppSettings

var functionAppSettings = union(commonAppSettings, planSpecificAppSettings)

  

module processingFunctionApp 'br/public:avm/res/web/site:0.16.0' = {
  name: processingFunctionAppName
  // scope: resourceGroup
  params: {
    kind: 'functionapp,linux'
    name: processingFunctionAppName
    location: location
    tags: union(tags , { 'azd-service-name' : 'processing' })
    serverFarmResourceId: hostingPlan.outputs.resourceId
    httpsOnly: true
    keyVaultAccessIdentityResourceId: uaiFrontendMsi.outputs.id
    managedIdentities: {
        systemAssigned: false
        userAssignedResourceIds: [
          uaiFrontendMsi.outputs.id
        ]
    }
    functionAppConfig: (functionAppHostPlan == 'FlexConsumption') ? {
      deployment: {
        storage: {
          type: 'blobContainer'
          value: '${procFuncStorage.outputs.primaryBlobEndpoint}${deploymentStorageContainerName}'
          authentication: { 
            type: 'UserAssignedIdentity'
            userAssignedIdentityResourceId: uaiFrontendMsi.outputs.id
          }
        }
      }
      scaleAndConcurrency: {
        maximumInstanceCount: 100
        instanceMemoryMB: 2048
      }
      runtime: { 
        name: functionRuntime
        version: '3.11'
      }
    } : null
    virtualNetworkSubnetId: _networkIsolation?vnet.outputs.appServicesSubId:''
    siteConfig: {
      alwaysOn: (functionAppHostPlan != 'FlexConsumption') ? true: null
      linuxFxVersion: (functionAppHostPlan != 'FlexConsumption') ? 'Python|3.11' : null
    }
    publicNetworkAccess: _networkIsolation?'Disabled':'Enabled'
    configs: [{
      name: 'appsettings'
      properties: functionAppSettings
    }]
  }
}

// Event Grid System Topic for bronze container blob events
// This must be created in Bicep (not auto-created) for reliable Event Grid subscription creation
// The Event Subscription is created in postDeploy.ps1/sh after the function code is deployed
var bronzeSystemTopicName = 'bronze-storage-topic-${suffix}'
module bronzeEventGridTopic 'br/public:avm/res/event-grid/system-topic:0.6.1' = {
  name: 'bronzeEventGridTopic'
  params: {
    name: bronzeSystemTopicName
    location: location
    tags: tags
    source: storage.outputs.id
    topicType: 'Microsoft.Storage.StorageAccounts'
  }
}

resource storageContributorRole 'Microsoft.Authorization/roleDefinitions@2022-05-01-preview' existing = {
  // scope: resourceGroup
  name: roles.storage.storageAccountContributor
}

resource storageDataOwnerRole 'Microsoft.Authorization/roleDefinitions@2022-05-01-preview' existing = {
  // scope: resourceGroup
  name: roles.storage.storageBlobDataOwner
}

resource storageQueueDataRole 'Microsoft.Authorization/roleDefinitions@2022-05-01-preview' existing = {
  // scope: resourceGroup
  name: roles.storage.storageQueueDataContributor
}

resource storageTableDataRole 'Microsoft.Authorization/roleDefinitions@2022-05-01-preview' existing = {
  // scope: resourceGroup
  name: roles.storage.storageTableDataContributor
}

resource storageFileContributorRole 'Microsoft.Authorization/roleDefinitions@2022-05-01-preview' existing = {
  // scope: resourceGroup
  name: roles.storage.storageFileDataPrivilegedContributor
}

var allstorageDataOwnerIdentityAssignments = concat([], [
  {
    principalId: uaiFrontendMsi.outputs.principalId
    roleDefinitionId: storageDataOwnerRole.id
    principalType: 'ServicePrincipal'
  }
])

module storageDataOwnerResourceGroupRoleAssignment './modules/security/resource-group-role-assignment.bicep' = {
  name: '${resourceGroupName}-role-storage-data-owner'
  // scope: resourceGroup
  params: {
    roleAssignments: (userPrincipalId != '') ? concat(allstorageDataOwnerIdentityAssignments, [{
      principalId: userPrincipalId
      roleDefinitionId: storageDataOwnerRole.id
      principalType: 'User'
    }]) : allstorageDataOwnerIdentityAssignments
  }
}

var allstorageQueueDataIdentityAssignments = concat([], [
  {
    principalId: uaiFrontendMsi.outputs.principalId
    roleDefinitionId: storageQueueDataRole.id
    principalType: 'ServicePrincipal'
  }
])

module storageQueueResourceGroupRoleAssignment './modules/security/resource-group-role-assignment.bicep' = {
  name: '${resourceGroupName}-role-storage-queue-data'
  // scope: resourceGroup
  params: {
    roleAssignments: (userPrincipalId != '') ? concat(allstorageQueueDataIdentityAssignments, [{
      principalId: userPrincipalId
      roleDefinitionId: storageDataOwnerRole.id
      principalType: 'User'
    }]) : allstorageQueueDataIdentityAssignments
  }
}

var allstorageTableDataIdentityAssignments = concat([], [
  {
    principalId: uaiFrontendMsi.outputs.principalId
    roleDefinitionId: storageTableDataRole.id
    principalType: 'ServicePrincipal'
  }
])

module storageTableResourceGroupRoleAssignment './modules/security/resource-group-role-assignment.bicep' = {
  name: '${resourceGroupName}-role-storage-table'
  // scope: resourceGroup
  params: {
    roleAssignments: (userPrincipalId != '') ? concat(allstorageTableDataIdentityAssignments, [{
      principalId: userPrincipalId
      roleDefinitionId: storageDataOwnerRole.id
      principalType: 'User'
    }]) : allstorageTableDataIdentityAssignments
  }
}

// Invoke the role assignment module for Storage Queue Data Contributor
var allstorageAccountContributorIdentityAssignments = concat([], [
  {
    principalId: uaiFrontendMsi.outputs.principalId
    roleDefinitionId: storageContributorRole.id
    principalType: 'ServicePrincipal'
  }
])


module storageAccountResourceGroupRoleAssignment './modules/security/resource-group-role-assignment.bicep' = {
  name: '${resourceGroupName}-role-storage-account-contributor'
  // scope: resourceGroup
  params: {
    roleAssignments: (userPrincipalId != '') ? concat(allstorageAccountContributorIdentityAssignments, [{
      principalId: userPrincipalId
      roleDefinitionId: storageContributorRole.id
      principalType: 'User'
    }]) : allstorageAccountContributorIdentityAssignments
  }
}

var allstorageFileContribIdentityAssignments = concat([], [
  {
    principalId: uaiFrontendMsi.outputs.principalId
    roleDefinitionId: storageFileContributorRole.id
    principalType: 'ServicePrincipal'
  }
]
)

module storageFileContribResourceGroupRoleAssignment './modules/security/resource-group-role-assignment.bicep' = {
  name: '${resourceGroupName}-role-storage-file-contributor'
  // scope: resourceGroup
  params: {
    roleAssignments: (userPrincipalId != '') ? concat(allstorageFileContribIdentityAssignments, [{
      principalId: userPrincipalId
      roleDefinitionId: storageFileContributorRole.id
      principalType: 'User'
    }]) : allstorageFileContribIdentityAssignments
  }
}

resource cogServicesUserRole 'Microsoft.Authorization/roleDefinitions@2022-05-01-preview' existing = {
  // scope: resourceGroup
  name: roles.ai.cognitiveServicesUser
}

var allcogServicesUserIdentityAssignments = concat([], [
  {
    principalId: uaiFrontendMsi.outputs.principalId
    roleDefinitionId: cogServicesUserRole.id
    principalType: 'ServicePrincipal'
  }
])


module cogServicesUserResourceGroupRoleAssignment './modules/security/resource-group-role-assignment.bicep' = {
  name: '${resourceGroupName}-role-cog-services-user'
  // scope: resourceGroup
  params: {
    roleAssignments: (userPrincipalId != '') ? concat(allcogServicesUserIdentityAssignments, [{
      principalId: userPrincipalId
      roleDefinitionId: cogServicesUserRole.id
      principalType: 'User'
    }]) : allcogServicesUserIdentityAssignments
  }
}

resource cogServicesOpenAIUserRole 'Microsoft.Authorization/roleDefinitions@2022-05-01-preview' existing = {
  // scope: resourceGroup
  name: roles.ai.cognitiveServicesOpenAIUser
}

var allcogServicesOpenAIUserIdentityAssignments = concat([], [
  {
    principalId: uaiFrontendMsi.outputs.principalId
    roleDefinitionId: cogServicesOpenAIUserRole.id
    principalType: 'ServicePrincipal'
  }
])


module cogServicesOpenAIUserResourceGroupRoleAssignment './modules/security/resource-group-role-assignment.bicep' = {
  name: '${resourceGroupName}-role-cog-services-openai-user'
  // scope: resourceGroup
  params: {
    roleAssignments: (userPrincipalId != '') ? concat(allcogServicesOpenAIUserIdentityAssignments, [{
      principalId: userPrincipalId
      roleDefinitionId: cogServicesOpenAIUserRole.id
      principalType: 'User'
    }]) : allcogServicesOpenAIUserIdentityAssignments
  }
}

resource contributorRole 'Microsoft.Authorization/roleDefinitions@2022-05-01-preview' existing = {
  // scope: resourceGroup
  name: roles.general.contributor
}

resource appConfigDataOwnerRole 'Microsoft.Authorization/roleDefinitions@2022-05-01-preview' existing = {
  // scope: resourceGroup
  name: roles.configuration.appConfigurationDataOwner
}

var appConfigDataOwnerIdentityAssignments = [
  for identity in identities: {
    principalId: identity.principalId
    roleDefinitionId: appConfigDataOwnerRole.id
    principalType: identity.principalType
  }
]

var allConfigDataOwnerIdentityAssignments = concat(appConfigDataOwnerIdentityAssignments, [
  {
    principalId: uaiFrontendMsi.outputs.principalId
    roleDefinitionId: appConfigDataOwnerRole.id
    principalType: 'ServicePrincipal'
  }
])

var contributorIdentityAssignments = [
  for identity in identities: {
    principalId: identity.principalId
    roleDefinitionId: contributorRole.id
    principalType: identity.principalType
  }
]

module resourceGroupRoleAssignment './modules/security/resource-group-role-assignment.bicep' = {
  name: '${resourceGroupName}-role-appconfig'
  // scope: resourceGroup
  params: {
    roleAssignments: (userPrincipalId != '') ? concat(contributorIdentityAssignments, allConfigDataOwnerIdentityAssignments, [{
      principalId: userPrincipalId
      roleDefinitionId: cogServicesOpenAIUserRole.id
      principalType: 'User'
    }]) : concat(contributorIdentityAssignments, [], allConfigDataOwnerIdentityAssignments)
  }
}

resource keyVaultSecretsUserRole 'Microsoft.Authorization/roleDefinitions@2022-05-01-preview' existing = {
  // scope: resourceGroup
  name: roles.security.keyVaultSecretsUser
}


// module testvm './modules/vm/dsvm.bicep' = if ((_networkIsolation && !_vnetReuse) || _deployVM)  {
//   scope : resourceGroup
//   name: 'testvm'
//   params: {
//     location: location
//     name: _ztVmName
//     tags: tags
//     subnetId: subnets['aiSubnet'].id
//     bastionSubId: subnets['AzureBastionSubnet'].id
//     vmUserPassword: vmUserInitialPassword
//     vmUserName: _vmUserName
//     keyVaultName: keyVault.outputs.name
//     vmUserPasswordKey: _vmKeyVaultSecName
//     principalId: principalId
//     azdEnvironmentName: environmentName
//   }
// }

// Bastion Host
module testVmBastionHost 'br/public:avm/res/network/bastion-host:0.8.0' = if (_deployVM && _networkIsolation) {
  // scope: resourceGroup
  name: 'bastionHost'
  params: {
    // Bastion host name
    name: '${abbrs.security.bastion}testvm-${suffix}'
    #disable-next-line BCP318
    virtualNetworkResourceId: vnet.outputs.id
    location: location
    skuName: 'Standard'
    tags: tags
    availabilityZones: []

    // Configuration for the Public IP that the module will create
    publicIPAddressObject: {
      // Name for the Public IP resource
      name: '${abbrs.networking.publicIPAddress}bastion-${suffix}'
      publicIPAllocationMethod: 'Static'
      skuName: 'Standard'
      skuTier: 'Regional'
      availabilityZones: []
      tags: tags
    }
  }
  // dependsOn: [
  //   #disable-next-line BCP321
  //   !useExistingVNet ? virtualNetwork : null
  //   #disable-next-line BCP321
  //   useExistingVNet ? virtualNetworkSubnets : null
  // ]
}

//AI Foundry Search User Managed Identity
module testVmUAI 'br/public:avm/res/managed-identity/user-assigned-identity:0.4.1' = if (_deployVM && _networkIsolation) {
  // // scope: resourceGroup
  name: '${abbrs.security.managedIdentity}${_ztVmName}'
  params: {
    // Required parameters
    name: '${abbrs.security.managedIdentity}${_ztVmName}'
    // Non-required parameters
    location: location
  }
}

// Test VM
module testVm 'br/public:avm/res/compute/virtual-machine:0.15.0' = if (_deployVM && _networkIsolation) {
  name: 'testVmDeployment'
  params: {
    name: _ztVmName
    location: location
    adminUsername: _vmUserName
    adminPassword: vmUserInitialPassword
    tags: tags
    managedIdentities: {
      systemAssigned: false
      #disable-next-line BCP318
      userAssignedResourceIds: [testVmUAI.outputs.resourceId]
    }
    imageReference: {
      publisher: vmImagePublisher
      offer:     vmImageOffer
      sku:       vmImageSku
      version:   vmImageVersion
    }
    encryptionAtHost: false 
    vmSize: vmSize
    osDisk: {
      caching: 'ReadWrite'
      diskSizeGB: 250
      managedDisk: {
        storageAccountType: 'Standard_LRS'
      }
      
    }
    osType: 'Windows'
    zone: 0
    nicConfigurations: [
      {
        nicSuffix: '-nic-01'
        ipConfigurations: [
          {
            name: 'ipconfig01'
            #disable-next-line BCP318
            subnetResourceId: vnet.outputs.aiSubId
          }
        ]
      }
    ]
  }
  // dependsOn: [
  //   testVmBastionHost
  //   #disable-next-line BCP321
  //   !useExistingVNet ? virtualNetwork : null
  //   #disable-next-line BCP321
  //   useExistingVNet ? virtualNetworkSubnets : null
  // ]
}

// var _fileUris = [
//   'https://raw.githubusercontent.com/Azure/GPT-RAG/refs/tags/${_manifest.tag}/infra/install.ps1'
// ]
var _fileUris = [
  'https://raw.githubusercontent.com/Azure/ai-document-processor/refs/heads/main/infra/install.ps1'
]


resource cse 'Microsoft.Compute/virtualMachines/extensions@2024-11-01' = if (_deployVM && _networkIsolation) {
  // // scope: ResourceGroup
  name: '${_ztVmName}/cse'
  location: location
  properties: {
    publisher: 'Microsoft.Compute'
    type: 'CustomScriptExtension' 
    typeHandlerVersion: '1.10'
    autoUpgradeMinorVersion: true
    forceUpdateTag: 'alwaysRun'
    settings: {
      fileUris: _fileUris
      commandToExecute:  'powershell.exe -ExecutionPolicy Unrestricted -File install.ps1 -AzureTenantId ${subscription().tenantId} -AzureSubscriptionId ${subscription().subscriptionId} -AzureResourceGroupName ${resourceGroup().name} -AzdEnvName ${environmentName}'
    }
    protectedSettings: {
      
    }
  }
  dependsOn: [
    testVm
    testVmBastionHost
  ]
}



// // Managed Identity Operator -> TestVm
// module assignManagedIdentityOperatorTestVm 'modules/security/resource-role-assignment.bicep' = if (deployVM && deployAppConfig && deployContainerRegistry && _networkIsolation) {
//   name: 'assignManagedIdentityOperatorTestVm'
//   params: {
//     name: 'assignManagedIdentityOperatorTestVm'
//     roleAssignments: [
//       {
//         roleDefinitionId: subscriptionResourceId(
//           'Microsoft.Authorization/roleDefinitions',
//           const.roles.ManagedIdentityOperator.guid
//         )
//         #disable-next-line BCP318
//         principalId: (_useUAI) ? testVmUAI.outputs.principalId : testVm.outputs.systemAssignedMIPrincipalId!
//         #disable-next-line BCP318
//         resourceId: ''
//         principalType: 'ServicePrincipal'
//       }
      
//     ]
//   }
// }



output RESOURCE_GROUP string = resourceGroup().name
output FUNCTION_APP_NAME string = processingFunctionApp.outputs.name
output AZURE_STORAGE_ACCOUNT string = storage.outputs.name
//jamespace
// output FUNCTION_URL string = processingFunctionApp.outputs.uri
output OPENAI_API_VERSION string = openaiApiVersion
// Migration: Construct endpoint from AVM output name
output OPENAI_API_BASE string = 'https://${aiFoundry.outputs.aiServicesName}.cognitiveservices.azure.com/'
output OPENAI_MODEL string = openaiModel
output FUNCTIONS_WORKER_RUNTIME string = functionRuntime
output PROCESSING_FUNCTION_APP_NAME string = processingFunctionApp.outputs.name
output PROCESSING_FUNCTION_URL string = 'https://${processingFunctionApp.outputs.defaultHostname}'
output APP_CONFIG_NAME string = appConfig.outputs.name
output KEY_VAULT_NAME string = keyVault.outputs.name
output COSMOS_DB_CONVERSATION_CONTAINER string = conversationHistoryContainerName
output COSMOS_DB_ACCOUNT_NAME string = cosmos.outputs.accountName
output COSMOS_DB_URI string = 'https://${cosmosAccountName}.documents.azure.com:443/'
output COSMOS_DB_DATABASE_NAME string = cosmos.outputs.databaseName
output FUNCTION_STORAGE_ACCOUNT string = procFuncStorage.outputs.name

// Event Grid outputs for postDeploy script
output BRONZE_SYSTEM_TOPIC_NAME string = bronzeSystemTopicName
output BRONZE_CONTAINER_NAME string = 'bronze'

// Resue details
@description('Settings to define reusable resources.')
var _azureReuseConfigDefaults = {
  aoaiReuse: false
  existingAoaiResourceGroupName: ''
  existingAoaiName: ''
  appInsightsReuse: false
  existingAppInsightsResourceGroupName: ''
  existingAppInsightsName: ''
  appConfigReuse: false
  existingAppConfigResourceGroupName: ''
  existingAppConfigName: ''
  logAnalyticsWorkspaceReuse: false  
  existingLogAnalyticsWorkspaceResourceId: ''
  appServicePlanReuse: false
  existingAppServicePlanResourceGroupName: ''
  existingAppServicePlanName: ''
  aiSearchReuse: false
  existingAiSearchResourceGroupName: ''
  existingAiSearchName: ''
  aiServicesReuse: false
  existingAiServicesResourceGroupName: ''
  existingAiServicesName: ''
  cosmosDbReuse: false
  existingCosmosDbResourceGroupName: ''
  existingCosmosDbAccountName: ''
  existingCosmosDbDatabaseName : ''
  keyVaultReuse: false
  existingKeyVaultResourceGroupName: ''
  existingKeyVaultName: ''
  storageReuse: false
  existingStorageResourceGroupName: ''
  existingStorageName: ''
  vnetReuse: false
  existingVnetResourceGroupName: ''
  existingVnetName: ''
  orchestratorFunctionAppReuse: false
  existingOrchestratorFunctionAppResourceGroupName: ''
  existingOrchestratorFunctionAppName: ''  
  dataIngestionFunctionAppReuse: false
  existingDataIngestionFunctionAppResourceGroupName: ''
  existingDataIngestionFunctionAppName: ''  
  appServiceReuse: false
  existingAppServiceName: ''
  existingAppServiceNameResourceGroupName: ''
  orchestratorFunctionAppStorageReuse: false
  existingOrchestratorFunctionAppStorageName: ''
  existingOrchestratorFunctionAppStorageResourceGroupName: ''
  dataIngestionFunctionAppStorageReuse: false
  existingDataIngestionFunctionAppStorageName: ''
  existingDataIngestionFunctionAppStorageResourceGroupName: ''  
}

param azureReuseConfig object = {} 
var _azureReuseConfig = union(_azureReuseConfigDefaults, {
    aoaiReuse: (empty(azureReuseConfig.aoaiReuse) ? _azureReuseConfigDefaults.aoaiReuse : toLower(azureReuseConfig.aoaiReuse) == 'true')
    existingAoaiResourceGroupName: (empty(azureReuseConfig.existingAoaiResourceGroupName) ? _azureReuseConfigDefaults.existingAoaiResourceGroupName : azureReuseConfig.existingAoaiResourceGroupName)
    existingAoaiName: (empty(azureReuseConfig.existingAoaiName) ? _azureReuseConfigDefaults.existingAoaiName : azureReuseConfig.existingAoaiName)
    aiServicesReuse: (empty(azureReuseConfig.aiServicesReuse) ? _azureReuseConfigDefaults.aiServicesReuse : toLower(azureReuseConfig.aiServicesReuse) == 'true')
    existingAiServicesResourceGroupName: (empty(azureReuseConfig.existingAiServicesResourceGroupName) ? _azureReuseConfigDefaults.existingAiServicesResourceGroupName : azureReuseConfig.existingAiServicesResourceGroupName)
    existingAiServicesName: (empty(azureReuseConfig.existingAiServicesName) ? _azureReuseConfigDefaults.existingAiServicesName : azureReuseConfig.existingAiServicesName)
    //appConfigReuse: (empty(azureReuseConfig.appConfigReuse) ? _azureReuseConfigDefaults.appConfigReuse : toLower(azureReuseConfig.appConfigReuse) == 'true')
    //existingAppConfigResourceGroupName: (empty(azureReuseConfig.existingAppConfigResourceGroupName) ? _azureReuseConfigDefaults.existingAppConfigResourceGroupName : azureReuseConfig.existingAppConfigResourceGroupName)
    //existingAppConfigName: (empty(azureReuseConfig.existingAppConfigName) ? _azureReuseConfigDefaults.existingAppConfigName : azureReuseConfig.existingAppConfigName)
    appConfigReuse: false
    existingAppConfigResourceGroupName: ''
    existingAppConfigName: ''
    appInsightsReuse: (empty(azureReuseConfig.appInsightsReuse) ? _azureReuseConfigDefaults.appInsightsReuse : toLower(azureReuseConfig.appInsightsReuse) == 'true')
    existingAppInsightsResourceGroupName: (empty(azureReuseConfig.existingAppInsightsResourceGroupName) ? _azureReuseConfigDefaults.existingAppInsightsResourceGroupName : azureReuseConfig.existingAppInsightsResourceGroupName)
    existingAppInsightsName: (empty(azureReuseConfig.existingAppInsightsName) ? _azureReuseConfigDefaults.existingAppInsightsName : azureReuseConfig.existingAppInsightsName)
    logAnalyticsWorkspaceReuse: (empty(azureReuseConfig.logAnalyticsWorkspaceReuse) ? _azureReuseConfigDefaults.logAnalyticsWorkspaceReuse : toLower(azureReuseConfig.logAnalyticsWorkspaceReuse) == 'true')
    existingLogAnalyticsWorkspaceResourceId: (empty(azureReuseConfig.existingLogAnalyticsWorkspaceResourceId) ? _azureReuseConfigDefaults.existingLogAnalyticsWorkspaceResourceId : azureReuseConfig.existingLogAnalyticsWorkspaceResourceId)
    appServicePlanReuse: (empty(azureReuseConfig.appServicePlanReuse) ? _azureReuseConfigDefaults.appServicePlanReuse : toLower(azureReuseConfig.appServicePlanReuse) == 'true')
    existingAppServicePlanResourceGroupName: (empty(azureReuseConfig.existingAppServicePlanResourceGroupName) ? _azureReuseConfigDefaults.existingAppServicePlanResourceGroupName : azureReuseConfig.existingAppServicePlanResourceGroupName)
    existingAppServicePlanName: (empty(azureReuseConfig.existingAppServicePlanName) ? _azureReuseConfigDefaults.existingAppServicePlanName : azureReuseConfig.existingAppServicePlanName)
    aiSearchReuse: (empty(azureReuseConfig.aiSearchReuse) ? _azureReuseConfigDefaults.aiSearchReuse : toLower(azureReuseConfig.aiSearchReuse) == 'true')
    existingAiSearchResourceGroupName: (empty(azureReuseConfig.existingAiSearchResourceGroupName) ? _azureReuseConfigDefaults.existingAiSearchResourceGroupName : azureReuseConfig.existingAiSearchResourceGroupName)
    existingAiSearchName: (empty(azureReuseConfig.existingAiSearchName) ? _azureReuseConfigDefaults.existingAiSearchName : azureReuseConfig.existingAiSearchName)
    cosmosDbReuse: (empty(azureReuseConfig.cosmosDbReuse) ? _azureReuseConfigDefaults.cosmosDbReuse : toLower(azureReuseConfig.cosmosDbReuse) == 'true')
    existingCosmosDbResourceGroupName: (empty(azureReuseConfig.existingCosmosDbResourceGroupName) ? _azureReuseConfigDefaults.existingCosmosDbResourceGroupName : azureReuseConfig.existingCosmosDbResourceGroupName)
    existingCosmosDbAccountName: (empty(azureReuseConfig.existingCosmosDbAccountName) ? _azureReuseConfigDefaults.existingCosmosDbAccountName : azureReuseConfig.existingCosmosDbAccountName)
    existingCosmosDbDatabaseName: (empty(azureReuseConfig.existingCosmosDbDatabaseName) ? _azureReuseConfigDefaults.existingCosmosDbDatabaseName : azureReuseConfig.existingCosmosDbDatabaseName)
    keyVaultReuse: (empty(azureReuseConfig.keyVaultReuse) ? _azureReuseConfigDefaults.keyVaultReuse : toLower(azureReuseConfig.keyVaultReuse) == 'true')
    existingKeyVaultResourceGroupName: (empty(azureReuseConfig.existingKeyVaultResourceGroupName) ? _azureReuseConfigDefaults.existingKeyVaultResourceGroupName : azureReuseConfig.existingKeyVaultResourceGroupName)
    existingKeyVaultName: (empty(azureReuseConfig.existingKeyVaultName) ? _azureReuseConfigDefaults.existingKeyVaultName : azureReuseConfig.existingKeyVaultName)
    storageReuse: (empty(azureReuseConfig.storageReuse) ? _azureReuseConfigDefaults.storageReuse : toLower(azureReuseConfig.storageReuse) == 'true')
    existingStorageResourceGroupName: (empty(azureReuseConfig.existingStorageResourceGroupName) ? _azureReuseConfigDefaults.existingStorageResourceGroupName : azureReuseConfig.existingStorageResourceGroupName)
    existingStorageName: (empty(azureReuseConfig.existingStorageName) ? _azureReuseConfigDefaults.existingStorageName : azureReuseConfig.existingStorageName)
    vnetReuse: (empty(azureReuseConfig.vnetReuse) ? _azureReuseConfigDefaults.vnetReuse : toLower(azureReuseConfig.vnetReuse) == 'true')
    existingVnetResourceGroupName: (empty(azureReuseConfig.existingVnetResourceGroupName) ? _azureReuseConfigDefaults.existingVnetResourceGroupName : azureReuseConfig.existingVnetResourceGroupName)
    existingVnetName: (empty(azureReuseConfig.existingVnetName) ? _azureReuseConfigDefaults.existingVnetName : azureReuseConfig.existingVnetName)
    orchestratorFunctionAppReuse: (empty(azureReuseConfig.orchestratorFunctionAppReuse) ? _azureReuseConfigDefaults.orchestratorFunctionAppReuse: toLower(azureReuseConfig.orchestratorFunctionAppReuse) == 'true')
    existingOrchestratorFunctionAppResourceGroupName: (empty(azureReuseConfig.existingOrchestratorFunctionAppResourceGroupName) ? _azureReuseConfigDefaults.existingOrchestratorFunctionAppResourceGroupName : azureReuseConfig.existingOrchestratorFunctionAppResourceGroupName)
    existingOrchestratorFunctionAppName: (empty(azureReuseConfig.existingOrchestratorFunctionAppName) ? _azureReuseConfigDefaults.existingOrchestratorFunctionAppName : azureReuseConfig.existingOrchestratorFunctionAppName)
    dataIngestionFunctionAppReuse: (empty(azureReuseConfig.dataIngestionFunctionAppReuse) ? _azureReuseConfigDefaults.dataIngestionFunctionAppReuse : toLower(azureReuseConfig.dataIngestionFunctionAppReuse) == 'true')
    existingDataIngestionFunctionAppResourceGroupName: (empty(azureReuseConfig.existingDataIngestionFunctionAppResourceGroupName) ? _azureReuseConfigDefaults.existingDataIngestionFunctionAppResourceGroupName : azureReuseConfig.existingDataIngestionFunctionAppResourceGroupName)
    existingDataIngestionFunctionAppName: (empty(azureReuseConfig.existingDataIngestionFunctionAppName) ? _azureReuseConfigDefaults.existingDataIngestionFunctionAppName : azureReuseConfig.existingDataIngestionFunctionAppName)
    appServiceReuse: (empty(azureReuseConfig.appServiceReuse) ? _azureReuseConfigDefaults.appServiceReuse : toLower(azureReuseConfig.appServiceReuse) == 'true')
    existingAppServiceName: (empty(azureReuseConfig.existingAppServiceName) ? _azureReuseConfigDefaults.existingAppServiceName : azureReuseConfig.existingAppServiceName)
    existingAppServiceNameResourceGroupName: (empty(azureReuseConfig.existingAppServiceNameResourceGroupName) ? _azureReuseConfigDefaults.existingAppServiceNameResourceGroupName : azureReuseConfig.existingAppServiceNameResourceGroupName)
    orchestratorFunctionAppStorageReuse: (empty(azureReuseConfig.orchestratorFunctionAppStorageReuse) ? _azureReuseConfigDefaults.orchestratorFunctionAppStorageReuse : toLower(azureReuseConfig.orchestratorFunctionAppStorageReuse) == 'true')
    existingOrchestratorFunctionAppStorageName: (empty(azureReuseConfig.existingOrchestratorFunctionAppStorageName) ? _azureReuseConfigDefaults.existingOrchestratorFunctionAppStorageName : azureReuseConfig.existingOrchestratorFunctionAppStorageName)
    existingOrchestratorFunctionAppStorageResourceGroupName: (empty(azureReuseConfig.existingOrchestratorFunctionAppStorageResourceGroupName) ? _azureReuseConfigDefaults.existingOrchestratorFunctionAppStorageResourceGroupName : azureReuseConfig.existingOrchestratorFunctionAppStorageResourceGroupName)
    dataIngestionFunctionAppStorageReuse: (empty(azureReuseConfig.dataIngestionFunctionAppStorageReuse) ? _azureReuseConfigDefaults.dataIngestionFunctionAppStorageReuse : toLower(azureReuseConfig.dataIngestionFunctionAppStorageReuse) == 'true')
    existingDataIngestionFunctionAppStorageName: (empty(azureReuseConfig.existingDataIngestionFunctionAppStorageName) ? _azureReuseConfigDefaults.existingDataIngestionFunctionAppStorageName : azureReuseConfig.existingDataIngestionFunctionAppStorageName)
    existingDataIngestionFunctionAppStorageResourceGroupName: (empty(azureReuseConfig.existingDataIngestionFunctionAppStorageResourceGroupName) ? _azureReuseConfigDefaults.existingDataIngestionFunctionAppStorageResourceGroupName : azureReuseConfig.existingDataIngestionFunctionAppStorageResourceGroupName)
  }
)
